#!/usr/bin/env python3

import os
import pyinotify
import zmq

NOTIFY_PORT = 6060

ZMQSocket = None

def setup_zmq():
    global ZMQSocket
    context = zmq.Context()
    socket = context.socket(zmq.PUB)
    socket.bind("tcp://10.0.0.2:%d" % NOTIFY_PORT)
    ZMQSocket = socket
    


class ProcessChangedFile(pyinotify.ProcessEvent):

    def process_IN_MODIFY(self, event):
        print ('\t', event.pathname, ' -> modify')
        ZMQSocket.send_string("notify:"+event.pathname)

    def process_default(self, event):
        print("default...",event.maskname)
        pass


def get_pwfile():
    return os.path.join("/etc", "passwd")

def get_groupfile():
    return os.path.join("/etc", "group")

def get_shadowfile():
    return os.path.join("/etc", "shadow")

def begin():
    setup_zmq()

    wm = pyinotify.WatchManager()

    notifier = pyinotify.Notifier(wm)

    wm.watch_transient_file(get_pwfile(), pyinotify.IN_MODIFY, ProcessChangedFile)
    #wm.watch_transient_file(get_groupfile(), pyinotify.IN_MODIFY, ProcessChangedFile)
    #wm.watch_transient_file(get_shadowfile(), pyinotify.IN_MODIFY, ProcessChangedFile)

    notifier.loop()

if __name__ == "__main__":
    begin()
